server:
  port: 9090

spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/HRAuth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

jwt:
  secretKey: ${secretKey}
  issuer: ${issuer}

rabbitmqKey:
  register-queue: register-queue
  auth-exchange: auth-exchange
  mail-queue: queue-mail
  mail-binding-key: mail-key
  register-binding: binding-register