server:
  port: 7075
spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/HRProjectMailService
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gizemliankaralilar@gmail.com
    password: nncgzgvysokjibye
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true