server:
  port: 7077
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  mail:
    host: smtp.gmail.com
    port: 587
    username: gizemliankaralilar@gmail.com
    password: nncgzgvysokjibye
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true