server:
  port: 7077
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: amine.gynk@gmail.com
    password: pmpfwgjngzqzdflz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true