server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27010
      username: team1
      password: root
      database: HRCompany

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: company-service

rabbitmqKey:
  auth-exchange: auth-exchange
  register-queue: register-queue
  register-binding-key: binding-key

