server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27010
      username: root
      password: 123456789
      database: HRCompany

rabbitmqKey:
  auth-exchange: auth-exchange
  register-binding-key: binding-key
  register-queue: register-queue
