server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**
          uri: http://localhost:9090
        - id: user-service
          predicates:
            - Path=/api/v1/user/**
          uri: http://localhost:9094
        - id: worker-service
          predicates:
            - Path=/api/v1/worker/**
          uri: http://localhost:9096
        - id: company-service
          predicates:
            - Path=/api/v1/company/**
          uri: http://localhost:9091
        - id: mail-service
          predicates:
            - Path=/api/v1/mail/**
          uri: http://localhost:7075