server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    globalcors:
      cors-configurations:
        '[/**]':
          allowed-origins: "*"
          allowed-headers: "*"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                 enabled: true
                 fallbackUri: forward:/fallback/auth_service


        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:9094
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user_service


        - id: worker-service
          predicates:
            - Path=/worker/**
          uri: http://localhost:9096
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/worker_service


        - id: company-service
          predicates:
            - Path=/company/**
          uri: http://localhost:9091
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/company_service


        - id: mail-service
          predicates:
            - Path=/mail/**
          uri: http://localhost:7075
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mail_service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}